# exec-once = uwsm-app -- my-service
# ターミナル経由やブラウザ経由で開きやすくするコマンド定義
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser
#$line = uwsm app -- LINE
$gmail = uwsm app -- gmail
$calendar = uwsm app -- google calender

# 起動時にスクラッチパッドに自動で送るアプリ
## Spotify
exec-once = [workspace special:dashboard;] spotify

## Youtube
#exec-once = [workspace special:dashboard;] $browser "https://youtube.com/"  # YouTube


## カレンダー
#exec-once = [workspace special:dashboard;] $calendar

## Btop(リソースモニター)
exec-once = [workspace special:dashboard;] $terminal -e btop

## LINE
exec-once = [workspace special:dashboard;] $browser  "chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/index.html#/friends" #LINE

exec-once = easyeffects

## 壁紙
#exec-once = pkill swaybg
exec-once = swww-daemon
exec-once = sleep 1 && ~/.config/hypr/scripts/wallpaper.sh

