general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[shell]
program = "zellij"
args = ["attach", "-c", "main"]

[font]
normal = { family = "Monaspace Neon Frozen" }
bold = { family = "Monaspace Neon Frozen" }
italic = { family = "Monaspace Neon Frozen" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"
